name: Master

on:
  push:
    branches:
      - master

jobs:
  gcr-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: >
          docker build -t eu.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/eq-questionnaire-launcher:latest .
      - name: Push
        env:
          DOCKER_BUILDKIT: 1
          GCLOUD_SERVICE_JSON: echo ${{ secrets.GCLOUD_SERVICE_KEY }}
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        run: |
          echo $GCLOUD_SERVICE_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io/
          docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/eq-questionnaire-launcher:latest


