name: PR

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: go get
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

  gcr-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag
        run: echo "TAG=${{ github.event.pull_request.head.ref }}" > $GITHUB_ENV
      - name: Build
        run: docker build -t onsdigital/eq-questionnaire-launcher:$TAG .
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: python -m base64 -e < ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: pete-test-env-on-release
          image_name: onsdigital/eq-questionnaire-launcher:$TAG

