name: PR

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: go get
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

  gcr-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: >
          docker build -t eu.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/eq-questionnaire-launcher:latest .
      - name: Push
        env:
          DOCKER_BUILDKIT: 1
          GCLOUD_SERVICE_JSON: ${{ secrets.GCLOUD_SERVICE_KEY }}
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          # Login to GCR
          echo $GCLOUD_SERVICE_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io/
          # Push Image
          docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/eq-questionnaire-launcher:latest
